<?xml version="1.0"?>
<package format="2">
  <name>n_desc</name>
  <version>0.0.0</version>
  <description>Reach Alpha 5 URDF and meshes, vendored from alpha_description.</description>
  <maintainer email="bolin@todo.todo">nknight</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <exec_depend>xacro</exec_depend>
  <exec_depend>urdf</exec_depend>
</package>
