<?xml version="1.0"?>
<package format="2">
  <name>n_pcloud</name>
  <version>0.0.0</version>
  <description>Point clouds in, obstacle field and grasp candidates out.</description>
  <maintainer email="bolin@todo.todo">nknight</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>python-numpy</exec_depend>
  <exec_depend>python-scipy</exec_depend>
</package>
