<?xml version="1.0"?>
<package format="2">
  <name>n_check</name>
  <version>0.0.0</version>
  <description>Is the arm clear, and can the jaws hold that. No ROS.</description>
  <maintainer email="bolin@todo.todo">nknight</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>n_kine</depend>
  <depend>n_conf</depend>
</package>
